name: 'Add comment'
on: [pull_request]

permissions:
  contents: read

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.NPM_AUTH_TOKEN }}
          script: |
            const artifactLink = `**[Link de teste](https://www.youtube.com)**`;
            const comment = `## Title\n\n${artifactLink}`;
            const payload = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            };
            await github.issues.createComment(payload);
